### ISSUE TITLE
Add Cloze Deletion?

### ISSUE THREAD

**Issue by dit7ya** [abo-abo/pamparam#14]
I miss org-drill's easy syntax of adding cloze deletions in the flashcards.

**Comment by abo-abo** [comment]
I don't know what cloze deletions are please explain.

**Comment by dit7ya** [comment]
This is a quick overview of cloze deletions. 

https://apps.ankiweb.net/docs/manual.html#cloze

It is basically hiding one part of the sentence rather than question and answer.

**Comment by abo-abo** [comment]
Thanks, please test.
