### ISSUE TITLE
Git path to binary

### ISSUE THREAD

**Issue by a-dma** [abo-abo/pamparam#15]
Hi,

I have an unconventional install of git on one of my computers that has a non-standard and non-exported path for the git binary. While I could add that location to the PATH, I was wondering if it were possible to add a configuration variable for that, something like the `magit-git-executable` variable used by magit.

**Comment by abo-abo** [comment]
I think it's easier for you to use:

```elisp
(add-to-list 'exec-path "path-to-git")
```

**Comment by a-dma** [comment]
Thanks, I ended up having to set both `exec-path` and `$PATH`: `shell-command` wasn't happy otherwise.

FYI, I ended up scrapping this experiment because the OS (Windows in that case) seemed generally unhappy about the structure of the git repository. I don't know if it was my weird setup or something else. The same thing seems to work on Linux.

Finally, I think there is a missing dependency on `lv` (which I believe is a transitive dependency of hydra but doesn't get installed). I had to install that manually to get things to work.
