### ISSUE TITLE
Is it possilbe to use this package without validation and do a self valdation

### ISSUE THREAD

**Issue by Anton-Latukha** [abo-abo/pamparam#17]
I would like to use this package for dictionaries, notes on topics.

But the requirement to enter answer perfectly does not fit for those cases.

If I pop in front of my eyes a heading of an article from a dictionary that has loose translations from one language to the other due to words not being directly translatable. Or headings regarding articles on technical topics - it is not possible to write bit-perfect answers to that.

I would be happy to see the topic, even the body of it, to not look but to restate that from memory and then check with the body text, and give myself a grade.

Is that is an easy thing to tweak & does it relate to:
```elisp
(defun pamparam-sm2 (card-stats q) ())
(defun pamparam-card-validate-maybe (&optional arg) ())
(defun pamparam-card-answer () ())
```

AKA just to skip the parts:
  * entering the answer, 
  * checking the answer,
  * automatically setting the rating.

And allow a human to see the body and assess the grade himself.

**Comment by abo-abo** [comment]
You can use this code in your config:

```elisp
(define-key pamparam-card-mode-map
    (kbd "C-c 5")
  (lambda ()
    (interactive)
    (revert-buffer nil t)
    (pamparam-card-score 5)))
```
