### ISSUE TITLE
S-TAB doesn't reveal the answer

### ISSUE THREAD

**Issue by daphniz** [abo-abo/pamparam#21]
Sorry if this is just caused by something else in my init, but `S-TAB` doesn't work for me, it just doesn't reveal the answer, or anything else.  I have no issues with `S-TAB` in other org files.

**Comment by abo-abo** [comment]
What does `<f1> k S-TAB` show?

**Comment by daphniz** [comment]
```
<backtab> (translated from <S-iso-lefttab>) runs the command
org-shifttab (found in org-mode-map), which is an interactive
compiled Lisp function ...
```

For now I'm using

	(define-key pamparam-card-mode-map (kbd "<backtab>") #'org-show-all)

**Comment by daphniz** [comment]
The problem seems to be that `org-shifttab` in this situation, where
the line is `^* ` and the cursor is not at column 0, does not
cycle but demotes (but there is nothing left to demote, so it
does nothing).

**Comment by abo-abo** [comment]
Thanks, please test.
