### ISSUE TITLE
Misplaces pampiles

### ISSUE THREAD

**Issue by daphniz** [abo-abo/pamparam#28]
For some reason, I tend to get misplaced pampiles.

		greek.pa % find -name 'pampile.org'
		./pampile.org
		./cards/71/pampile.org
		./cards/41/pampile.org
		./cards/a8/pampile.org
		./cards/e3/pampile.org
		./cards/cd/pampile.org

**Comment by daphniz** [comment]
This seems to happen when `-check` is called from a card file.  I didn't realize that wasn't supposed to be done.

**Comment by abo-abo** [comment]
Thanks. Would be nice to pinpoint a reproducible scenario which leads to the inconsistencies that `pamparam-check` fixes. Ideally, we should not have the inconsistencies in the first place.
