### ISSUE TITLE
if: Command failed: echo -e '* m\n#+STARTUP: content\n* Queen\ngood' > /home/tuhdo/workspace/test/masterfile.pam/cards/2c/2c2d2c0291163b077a372c2a9c5a6eda-755f85c2723bb39381c7379a604160d8.org

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/pamparam#3]
It seems like some directories cannot be created and the file cannot be written.

**Comment by abo-abo** [comment]
This is probably due to a recent change that makes that file name `cards/2c/2c2d....org` instead of `cards/2c2d...org`. I'll fix it soon.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by tuhdo** [comment]
I got another error:

```
file-truename: Variable binding depth exceeds max-specpdl-size
```

After following the example `capitals.org` in the repo.

**Comment by abo-abo** [comment]
> file-truename

I don't see `file-truename` used anywhere in `pamparam.el`.
