### ISSUE TITLE
worf?

### ISSUE THREAD

**Issue by idontgetoutmuch** [abo-abo/pamparam#5]
```
pamparam.el:35:1:Error: Cannot open load file: No such file or directory, worf
```

**Comment by abo-abo** [comment]
You can install `worf` from MELPA. On line 8 of `pamparam.el` you can see all dependencies:

    ;; Package-Requires: ((emacs "24.3") (lispy "0.26.0") (worf "0.1.0") (hydra "0.13.4"))
