### ISSUE TITLE
Command pamparam-sync failed on windows

### ISSUE THREAD

**Issue by lislon** [abo-abo/pamparam#7]
#### Description :octocat:
When run `pamparam-sync` command on windows 7 it fails

#### Reproduction guide :beetle:
- Start emacs on windows 7
- Open `doc/sets/capitals/capitals.org`
- Run `pamparam-sync`

#### Observed behaviour:  :eyes: :broken_heart:

The `-p` directory created and I see error:
```
pamparam-update-card: Command failed: mkdir -p "c:/Users/Elephant/src/elisp/pamparam/doc/sets/capitals/capitals.pam/cards/03/" && echo -e "* m\n#+STARTUP: content\n* France\nParis" > "c:/Users/Elephant/src/elisp/pamparam/doc/sets/capitals/capitals.pam/cards/03/0309a6c666a7a803fdb9db95de71cf01-e20d37a5d7fcc4c35be6fc18a8e71bfa.org"
```

#### Expected behaviour: :heart: :smile:

Command succeeds

#### System Info :computer:

- OS: windows 7
- Emacs: 24.5.1
- Git version 2.10.1.windows.1
- %PATH%: "c:\Program Files\Git\usr\bin:...other-directories" 

#### Workaround

The workaround is to put mkdir into quotes:

```elisp
;; pamparam.el
(cmd (format "\"mkdir\" -p %s && echo -e %s > %s"
```

Related topic: https://superuser.com/questions/856582/force-windows-use-exe-on-path-rather-than-cmd-exe-internal-command.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by lislon** [comment]
Sorry, forgot to mention that echo command has the same issue

**Comment by abo-abo** [comment]
Try it now. Should work, although much slower than on Linux.
