### ISSUE TITLE
repo issues

### ISSUE THREAD

**Issue by yitang** [abo-abo/pamparam#8]
thanks for writing this package. I have been looking for something like this for since two years ago.

I followed your youtube video and tried myself, I noticed the repo issues:

I only have one Master file and it only works if I set the following:

```emacs-lisp
(setq pam-alist
      '(("~/git/memory/english.org"
	 . "~/git/memory/pam/english.pam")))
(setq pamparam-path "~/git/memory/pam/english.pam")
```

otherwise, the repo will be created in where pamparam installed. In my case, it was a git repo, and when I try to pam-commit, it git-commit the whole git repo, not just the cards repo. luckily there's nothing harmful.

because of this setting, I think there will be probelms for people having multiple master files.

**Comment by abo-abo** [comment]
Thanks, I updated the defaults to make more sense.

Keeping multiple master files around is indeed tricky. The idea is that if you're in the correct directory, things should work with the corresponding repository.

If you notice that's not the case, issue reports and PRs are welcome.
